import type { Metadata } from "next";
import "./globals.css";
import ReactQueryProvider from "../reactQueryProvider/ReactQueryProvider";

export const metadata: Metadata = {
  title: "Slothui",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-poppin overflow-x-hidden"> 
        <ReactQueryProvider>{children}</ReactQueryProvider>
    </body>
    </html>
  );
}
